#!/bin/bash

mydir=`dirname $0`
domains=`${mydir}/list-avahi-web-services | tr "\\n" " "`

echo "Found domains: ${domains}"
if [ "${domains}" == "" ]; then
    echo "No domains, exiting."
    exit 1
fi
echo "Starting publisher... Hit Ctrl-C to end."
${mydir}/addalias.py ${domains}
